export const BACKGROUNDS = [
  {
    id: 'rymden',
    name: 'Rymden',
    emoji: '🚀',
    gradient: 'linear-gradient(180deg, #0a0a2e 0%, #1a1a6e 100%)',
    groundColor: '#0d0d40',
    accentColor: '#4040ff',
    stars: true,
    description: 'Bland stjärnor och planeter!',
  },
  {
    id: 'prinsessa',
    name: 'Prinsessa',
    emoji: '👸',
    gradient: 'linear-gradient(180deg, #ffb3d9 0%, #ff69b4 100%)',
    groundColor: '#ff1493',
    accentColor: '#fff0f8',
    stars: false,
    description: 'Sagolikt slott med glitter!',
  },
  {
    id: 'dinosaurier',
    name: 'Dinosaurier',
    emoji: '🦕',
    gradient: 'linear-gradient(180deg, #2d5a00 0%, #4a8a00 100%)',
    groundColor: '#3a6600',
    accentColor: '#aaff44',
    stars: false,
    description: 'Urtidsdjur och vulkaner!',
  },
  {
    id: 'havet',
    name: 'Havet',
    emoji: '🐠',
    gradient: 'linear-gradient(180deg, #006994 0%, #0099cc 100%)',
    groundColor: '#c4a55a',
    accentColor: '#00ccff',
    stars: false,
    description: 'Koraller och fiskar under ytan!',
  },
  {
    id: 'halloween',
    name: 'Halloween',
    emoji: '🎃',
    gradient: 'linear-gradient(180deg, #1a0a2e 0%, #4a1a00 100%)',
    groundColor: '#1a1a1a',
    accentColor: '#ff6600',
    stars: true,
    description: 'Spöken och pumpalyktor!',
  },
  {
    id: 'djungeln',
    name: 'Djungeln',
    emoji: '🦁',
    gradient: 'linear-gradient(180deg, #1a3a1a 0%, #2d5a2d 100%)',
    groundColor: '#4a7a1a',
    accentColor: '#88ff44',
    stars: false,
    description: 'Vilda djur i tät skog!',
  },
  {
    id: 'sport',
    name: 'Sport',
    emoji: '⚽',
    gradient: 'linear-gradient(180deg, #1e3a5f 0%, #3a7bd5 100%)',
    groundColor: '#2d6a2d',
    accentColor: '#ffffff',
    stars: false,
    description: 'Spela och vinn guld!',
  },
  {
    id: 'saga',
    name: 'Saga',
    emoji: '🏰',
    gradient: 'linear-gradient(180deg, #2a0a4a 0%, #6a2aaa 100%)',
    groundColor: '#3a1a6a',
    accentColor: '#ffdd44',
    stars: true,
    description: 'Riddare och drakar!',
  },
  {
    id: 'vilda_vastern',
    name: 'Vilda Västern',
    emoji: '🤠',
    gradient: 'linear-gradient(180deg, #8b4513 0%, #d2691e 100%)',
    groundColor: '#c8a05a',
    accentColor: '#ff8c00',
    stars: false,
    description: 'Cowboys och öken!',
  },
  {
    id: 'superhjältar',
    name: 'Superhjältar',
    emoji: '🦸',
    gradient: 'linear-gradient(180deg, #1a1a3e 0%, #2a2a8e 100%)',
    groundColor: '#1a1a2e',
    accentColor: '#ff2244',
    stars: true,
    description: 'Rädda världen!',
  },
  {
    id: 'framtiden',
    name: 'Framtiden',
    emoji: '🤖',
    gradient: 'linear-gradient(180deg, #001122 0%, #002244 100%)',
    groundColor: '#003366',
    accentColor: '#00ffcc',
    stars: true,
    description: 'Robotar och rymdstäder!',
  },
  {
    id: 'pirater',
    name: 'Pirater',
    emoji: '🏴‍☠️',
    gradient: 'linear-gradient(180deg, #0a2a4a 0%, #1a5a8a 100%)',
    groundColor: '#c4a55a',
    accentColor: '#ffd700',
    stars: false,
    description: 'Skattjakt på havet!',
  },
  {
    id: 'magi',
    name: 'Magi',
    emoji: '✨',
    gradient: 'linear-gradient(180deg, #1a0a3e 0%, #4a0a8e 100%)',
    groundColor: '#2a0a5e',
    accentColor: '#ffaaff',
    stars: true,
    description: 'Trollstavar och magi!',
  },
  {
    id: 'mat',
    name: 'Mat',
    emoji: '🍕',
    gradient: 'linear-gradient(180deg, #ff6600 0%, #ffaa00 100%)',
    groundColor: '#cc4400',
    accentColor: '#ffffff',
    stars: false,
    description: 'Läckra maträtter!',
  },
  {
    id: 'musik',
    name: 'Musik',
    emoji: '🎵',
    gradient: 'linear-gradient(180deg, #0a0a1e 0%, #2a1a4e 100%)',
    groundColor: '#1a1a3e',
    accentColor: '#a78bfa',
    stars: true,
    description: 'Dansa och sjung!',
  },
  {
    id: 'djur',
    name: 'Djur',
    emoji: '🐶',
    gradient: 'linear-gradient(180deg, #2d6a2d 0%, #4a9a2d 100%)',
    groundColor: '#5a8a1a',
    accentColor: '#ffdd44',
    stars: false,
    description: 'Söta djur överallt!',
  },
  {
    id: 'godis',
    name: 'Godis',
    emoji: '🍭',
    gradient: 'linear-gradient(180deg, #ff66aa 0%, #ffaacc 100%)',
    groundColor: '#ff3388',
    accentColor: '#ffffff',
    stars: false,
    description: 'Sockersöt värld!',
  },
  {
    id: 'polar',
    name: 'Polar',
    emoji: '🐧',
    gradient: 'linear-gradient(180deg, #aaddff 0%, #ddeeff 100%)',
    groundColor: '#ffffff',
    accentColor: '#0066aa',
    stars: false,
    description: 'Is och snö med pingviner!',
  },
];

export function getBackground(id) {
  return BACKGROUNDS.find(b => b.id === id) || BACKGROUNDS[0];
}
