export const WIZARD_CONFIG = {
  spel: {
    label: 'Spel',
    emoji: '🎮',
    color: '#2d7dd2',
    steps: [
      {
        id: 'speltyp',
        question: 'Vad för spel?',
        type: 'choice',
        choices: [
          { id: 'platform', label: 'Plattform', emoji: '🏃' },
          { id: 'obby', label: 'Obby', emoji: '🧱' },
          { id: 'runner', label: 'Runner', emoji: '🌀' },
          { id: 'shooter', label: 'Shooter', emoji: '💥' },
          { id: 'mystery', label: 'Mystery', emoji: '🔍' },
          { id: 'labyrint', label: 'Labyrint', emoji: '🌿' },
        ],
      },
      {
        id: 'karaktar',
        question: 'Vem är din karaktär?',
        type: 'choice',
        choices: [
          { id: 'ninja', label: 'Ninja', emoji: '🥷' },
          { id: 'robot', label: 'Robot', emoji: '🤖' },
          { id: 'dinosaurie', label: 'Dinosaurie', emoji: '🦕' },
          { id: 'enhornin', label: 'Enhörning', emoji: '🦄' },
          { id: 'rymdalien', label: 'Rymdalien', emoji: '👽' },
          { id: 'pirat', label: 'Pirat', emoji: '🏴‍☠️' },
          { id: 'trollet', label: 'Trollet', emoji: '🧌' },
          { id: 'vampyren', label: 'Vampyren', emoji: '🧛' },
          { id: 'haxan', label: 'Häxan', emoji: '🧙‍♀️' },
          { id: 'riddaren', label: 'Riddaren', emoji: '⚔️' },
          { id: 'astronauten', label: 'Astronauten', emoji: '👨‍🚀' },
          { id: 'havsfrun', label: 'Havsfrun', emoji: '🧜' },
          { id: 'varulven', label: 'Varulven', emoji: '🐺' },
          { id: 'draken', label: 'Draken', emoji: '🐉' },
          { id: 'pandahjälten', label: 'Pandahjälten', emoji: '🐼' },
          { id: 'spindeln', label: 'Spindeln', emoji: '🕷️' },
        ],
      },
      {
        id: 'varld',
        question: 'Vilken värld?',
        type: 'choice',
        choices: [
          { id: 'rymden', label: 'Rymden', emoji: '🚀' },
          { id: 'djungeln', label: 'Djungeln', emoji: '🌿' },
          { id: 'havet', label: 'Havet', emoji: '🌊' },
          { id: 'staden', label: 'Staden', emoji: '🏙️' },
          { id: 'dromvarlden', label: 'Drömvärlden', emoji: '✨' },
          { id: 'vulkanen', label: 'Vulkanen', emoji: '🌋' },
          { id: 'istiden', label: 'Istiden', emoji: '❄️' },
          { id: 'skogen', label: 'Skogen', emoji: '🌲' },
          { id: 'sandoknen', label: 'Sandöknen', emoji: '🏜️' },
          { id: 'arktis', label: 'Arktis', emoji: '🧊' },
          { id: 'undervattnet', label: 'Undervattnet', emoji: '🐠' },
          { id: 'halloweenstaden', label: 'Halloweenstaden', emoji: '🎃' },
          { id: 'candyland', label: 'Candyland', emoji: '🍭' },
          { id: 'ingenstandsland', label: 'Landet Ingenstans', emoji: '🌀' },
        ],
      },
      {
        id: 'fiende',
        question: 'Vad är fienden?',
        type: 'choice',
        choices: [
          { id: 'monster', label: 'Monster', emoji: '👹' },
          { id: 'robotar', label: 'Robotar', emoji: '🤖' },
          { id: 'fiskar', label: 'Fiskar', emoji: '🐟' },
          { id: 'bomber', label: 'Bomber', emoji: '💣' },
          { id: 'spoken', label: 'Spöken', emoji: '👻' },
          { id: 'inga', label: 'Inga', emoji: '❌' },
        ],
      },
      {
        id: 'svarighet',
        question: 'Hur svårt?',
        type: 'slider',
        min: 1,
        max: 10,
        step: 1,
        minLabel: 'Lätt',
        maxLabel: 'Svårt',
        default: 5,
      },
    ],
  },

  musik: {
    label: 'Musik Studio',
    emoji: '🎵',
    color: '#6c3bbd',
    steps: [
      {
        id: 'genre',
        question: 'Vilken genre?',
        type: 'choice',
        choices: [
          { id: 'pop', label: 'Pop', emoji: '🎤' },
          { id: 'hiphop', label: 'Hip-hop', emoji: '🔥' },
          { id: 'rock', label: 'Rock', emoji: '🎸' },
          { id: 'elektronisk', label: 'Elektronisk', emoji: '⚡' },
          { id: 'jazz', label: 'Jazz', emoji: '🎷' },
          { id: 'klassisk', label: 'Klassisk', emoji: '🎻' },
          { id: 'reggae', label: 'Reggae', emoji: '🌴' },
          { id: 'metal', label: 'Metal', emoji: '🤘' },
          { id: 'country', label: 'Country', emoji: '🤠' },
          { id: 'kpop', label: 'K-Pop', emoji: '🌸' },
        ],
      },
      {
        id: 'stamning',
        question: 'Vilken stämning?',
        type: 'choice',
        choices: [
          { id: 'glad', label: 'Glad', emoji: '😄' },
          { id: 'mystisk', label: 'Mystisk', emoji: '🌙' },
          { id: 'episk', label: 'Episk', emoji: '⚔️' },
          { id: 'lugn', label: 'Lugn', emoji: '🌊' },
          { id: 'galen', label: 'Galen', emoji: '🤪' },
          { id: 'laskig', label: 'Läskig', emoji: '👻' },
          { id: 'dansvänlig', label: 'Dansvänlig', emoji: '💃' },
          { id: 'drömsk', label: 'Drömsk', emoji: '💭' },
          { id: 'triumferande', label: 'Triumferande', emoji: '🏆' },
        ],
      },
      {
        id: 'instrument',
        question: 'Välj 2 instrument!',
        type: 'multiChoice',
        min: 2,
        max: 2,
        choices: [
          { id: 'piano', label: 'Piano', emoji: '🎹' },
          { id: 'trummor', label: 'Trummor', emoji: '🥁' },
          { id: 'gitarr', label: 'Gitarr', emoji: '🎸' },
          { id: 'synth', label: 'Synth', emoji: '🎛️' },
          { id: 'trumpet', label: 'Trumpet', emoji: '🎺' },
          { id: 'violin', label: 'Violin', emoji: '🎻' },
          { id: 'bas', label: 'Bas', emoji: '🎵' },
          { id: 'slagverk', label: 'Slagverk', emoji: '🪘' },
          { id: 'harpa', label: 'Harpa', emoji: '🪗' },
          { id: 'orgel', label: 'Orgel', emoji: '🎹' },
        ],
      },
      {
        id: 'tempo',
        question: 'Vilket tempo?',
        type: 'slider',
        min: 1,
        max: 10,
        step: 1,
        minLabel: 'Långsamt',
        maxLabel: 'Snabbt',
        default: 5,
      },
    ],
  },

  ritprogram: {
    label: 'Ritprogram',
    emoji: '🎨',
    color: '#e84855',
    steps: [
      {
        id: 'motiv',
        question: 'Vad ska du rita?',
        type: 'choice',
        choices: [
          { id: 'landskap', label: 'Landskap', emoji: '🌄' },
          { id: 'portratt', label: 'Porträtt', emoji: '👤' },
          { id: 'abstrakt', label: 'Abstrakt', emoji: '🌈' },
          { id: 'djur', label: 'Djur', emoji: '🐾' },
          { id: 'stad', label: 'Stad', emoji: '🏙️' },
          { id: 'rymd', label: 'Rymd', emoji: '🚀' },
        ],
      },
      {
        id: 'stil',
        question: 'Vilken stil?',
        type: 'choice',
        choices: [
          { id: 'tecknad', label: 'Tecknad', emoji: '✏️' },
          { id: 'pixel', label: 'Pixel', emoji: '🟦' },
          { id: 'realistisk', label: 'Realistisk', emoji: '🖼️' },
          { id: 'psychedelic', label: 'Psychedelic', emoji: '🌀' },
          { id: 'minimalistisk', label: 'Minimalistisk', emoji: '⬜' },
        ],
      },
      {
        id: 'palett',
        question: 'Vilken färgpalett?',
        type: 'choice',
        choices: [
          { id: 'regnbage', label: 'Regnbåge', emoji: '🌈' },
          { id: 'pastell', label: 'Pastell', emoji: '🌸' },
          { id: 'mork', label: 'Mörk', emoji: '🌑' },
          { id: 'neon', label: 'Neon', emoji: '💡' },
          { id: 'naturlig', label: 'Naturlig', emoji: '🍃' },
          { id: 'svartvit', label: 'Svartvit', emoji: '⬛' },
        ],
      },
    ],
  },

  filmstudio: {
    label: 'Filmstudio',
    emoji: '🎬',
    color: '#c33c54',
    steps: [
      {
        id: 'genre',
        question: 'Vilken filmgenre?',
        type: 'choice',
        choices: [
          { id: 'aventyr', label: 'Äventyr', emoji: '⚔️' },
          { id: 'komedi', label: 'Komedi', emoji: '😂' },
          { id: 'skrack', label: 'Skräck', emoji: '👻' },
          { id: 'scifi', label: 'Sci-fi', emoji: '🚀' },
          { id: 'saga', label: 'Saga', emoji: '🧚' },
          { id: 'superhjälte', label: 'Superhjälte', emoji: '🦸' },
        ],
      },
      {
        id: 'hjalte',
        question: 'Vem är hjälten?',
        type: 'choice',
        choices: [
          { id: 'ninja', label: 'Ninja', emoji: '🥷' },
          { id: 'robot', label: 'Robot', emoji: '🤖' },
          { id: 'prinsessa', label: 'Prinsessa', emoji: '👸' },
          { id: 'superhjälte', label: 'Superhjälte', emoji: '🦸' },
          { id: 'detektiv', label: 'Detektiv', emoji: '🕵️' },
          { id: 'magiker', label: 'Magiker', emoji: '🧙' },
        ],
      },
      {
        id: 'skurk',
        question: 'Vem är skurken?',
        type: 'choice',
        choices: [
          { id: 'drake', label: 'Drake', emoji: '🐉' },
          { id: 'alien', label: 'Alien', emoji: '👾' },
          { id: 'häxa', label: 'Häxa', emoji: '🧙‍♀️' },
          { id: 'pirat', label: 'Pirat', emoji: '🏴‍☠️' },
          { id: 'spöke', label: 'Spöke', emoji: '👻' },
          { id: 'ondrobot', label: 'Ond robot', emoji: '🤖' },
        ],
      },
      {
        id: 'miljo',
        question: 'Var utspelar det sig?',
        type: 'choice',
        choices: [
          { id: 'skog', label: 'Skog', emoji: '🌲' },
          { id: 'rymden', label: 'Rymden', emoji: '🚀' },
          { id: 'stad', label: 'Stad', emoji: '🏙️' },
          { id: 'slott', label: 'Slott', emoji: '🏰' },
          { id: 'hav', label: 'Hav', emoji: '🌊' },
          { id: 'vulkan', label: 'Vulkan', emoji: '🌋' },
        ],
      },
      {
        id: 'slut',
        question: 'Hur slutar filmen?',
        type: 'choice',
        choices: [
          { id: 'glad', label: 'Glad', emoji: '🎊' },
          { id: 'cliffhanger', label: 'Cliffhanger', emoji: '😱' },
          { id: 'roligt', label: 'Roligt', emoji: '😄' },
          { id: 'mysterium', label: 'Mysterium', emoji: '🔍' },
        ],
      },
    ],
  },

  kortspel: {
    label: 'Kortspel',
    emoji: '🃏',
    color: '#5c6bc0',
    steps: [
      {
        id: 'speltyp',
        question: 'Vad för kortspel?',
        type: 'choice',
        choices: [
          { id: 'memory', label: 'Memory', emoji: '🧠' },
          { id: 'snap', label: 'Snap', emoji: '⚡' },
          { id: 'toptrumps', label: 'Top Trumps', emoji: '🏆' },
          { id: 'gofish', label: 'Go Fish', emoji: '🐟' },
        ],
      },
      {
        id: 'tema',
        question: 'Vilket tema?',
        type: 'choice',
        choices: [
          { id: 'djur', label: 'Djur', emoji: '🐾' },
          { id: 'rymden', label: 'Rymden', emoji: '🚀' },
          { id: 'mat', label: 'Mat', emoji: '🍕' },
          { id: 'sport', label: 'Sport', emoji: '⚽' },
          { id: 'dinosaurier', label: 'Dinosaurier', emoji: '🦕' },
          { id: 'superhjältar', label: 'Superhjältar', emoji: '🦸' },
          { id: 'pirater', label: 'Pirater', emoji: '☠️' },
          { id: 'framtiden', label: 'Framtiden', emoji: '🤖' },
          { id: 'hajar', label: 'Hajar', emoji: '🦈' },
          { id: 'sagofigurer', label: 'Sagofigurer', emoji: '🧚' },
          { id: 'jul', label: 'Jul', emoji: '🎄' },
          { id: 'halloween', label: 'Halloween', emoji: '🎃' },
          { id: 'musikinstrument', label: 'Musikinstrument', emoji: '🎸' },
          { id: 'yrken', label: 'Yrken', emoji: '👩‍🚀' },
          { id: 'sverige', label: 'Sverige', emoji: '🇸🇪' },
        ],
      },
      {
        id: 'svarighet',
        question: 'Hur svårt?',
        type: 'choice',
        choices: [
          { id: 'latt', label: 'Lätt', emoji: '😊' },
          { id: 'lagom', label: 'Lagom', emoji: '😐' },
          { id: 'svart', label: 'Svårt', emoji: '😤' },
        ],
      },
    ],
  },

  bradspel: {
    label: 'Brädspel',
    emoji: '🎲',
    color: '#8d6748',
    steps: [
      {
        id: 'speltyp',
        question: 'Vad för brädspel?',
        type: 'choice',
        choices: [
          { id: 'banspel', label: 'Banspel', emoji: '🛤️' },
          { id: 'strategi', label: 'Strategi', emoji: '♟️' },
          { id: 'trivia', label: 'Trivia', emoji: '❓' },
          { id: 'jakten', label: 'Jakten', emoji: '🏃' },
        ],
      },
      {
        id: 'tema',
        question: 'Vilket tema?',
        type: 'choice',
        choices: [
          { id: 'pirater', label: 'Pirater', emoji: '☠️' },
          { id: 'rymden', label: 'Rymden', emoji: '🚀' },
          { id: 'djungeln', label: 'Djungeln', emoji: '🌿' },
          { id: 'medeltiden', label: 'Medeltiden', emoji: '⚔️' },
          { id: 'framtiden', label: 'Framtiden', emoji: '🤖' },
        ],
      },
      {
        id: 'spelare',
        question: 'Hur många spelare?',
        type: 'choice',
        choices: [
          { id: '2', label: '2 spelare', emoji: '👥' },
          { id: '3', label: '3 spelare', emoji: '👥👤' },
          { id: '4', label: '4 spelare', emoji: '👥👥' },
        ],
      },
      {
        id: 'svarighet',
        question: 'Hur svårt?',
        type: 'choice',
        choices: [
          { id: 'latt', label: 'Lätt', emoji: '😊' },
          { id: 'lagom', label: 'Lagom', emoji: '😐' },
          { id: 'svart', label: 'Svårt', emoji: '😤' },
        ],
      },
    ],
  },

  larospel: {
    label: 'Lärospel',
    emoji: '🧠',
    color: '#00897b',
    steps: [
      {
        id: 'amne',
        question: 'Vilket ämne?',
        type: 'choice',
        choices: [
          { id: 'matte', label: 'Matte', emoji: '➕' },
          { id: 'svenska', label: 'Svenska', emoji: '📖' },
          { id: 'geografi', label: 'Geografi', emoji: '🌍' },
          { id: 'natur', label: 'Natur', emoji: '🌱' },
          { id: 'historia', label: 'Historia', emoji: '🏛️' },
          { id: 'engelska', label: 'Engelska', emoji: '🇬🇧' },
        ],
      },
      {
        id: 'format',
        question: 'Vilket format?',
        type: 'choice',
        choices: [
          { id: 'quiz', label: 'Quiz', emoji: '🎯' },
          { id: 'memory', label: 'Memory', emoji: '🧠' },
          { id: 'snabbsvar', label: 'Snabbsvar', emoji: '⚡' },
          { id: 'draochslapp', label: 'Dra-och-släpp', emoji: '🖱️' },
        ],
      },
      {
        id: 'svarighet',
        question: 'Hur svårt?',
        type: 'choice',
        choices: [
          { id: 'latt', label: 'Lätt', emoji: '😊' },
          { id: 'lagom', label: 'Lagom', emoji: '😐' },
          { id: 'svart', label: 'Svårt', emoji: '😤' },
        ],
      },
    ],
  },

  rostlab: {
    label: 'Röstlab',
    emoji: '🎤',
    color: '#e53935',
    steps: [
      {
        id: 'effekt',
        question: 'Vilken rösteffekt?',
        type: 'choice',
        choices: [
          { id: 'robot', label: 'Robot', emoji: '🤖' },
          { id: 'chipmunk', label: 'Chipmunk', emoji: '🐿️' },
          { id: 'monster', label: 'Monster', emoji: '👹' },
          { id: 'echo', label: 'Echo', emoji: '🔊' },
          { id: 'reverb', label: 'Reverb', emoji: '🌊' },
          { id: 'pitchupp', label: 'Pitch upp', emoji: '⬆️' },
        ],
      },
      {
        id: 'loop',
        question: 'Loopa eller spela in?',
        type: 'choice',
        choices: [
          { id: 'loopa', label: 'Ja loopa', emoji: '🔁' },
          { id: 'bara', label: 'Bara spela in', emoji: '🎙️' },
        ],
      },
      {
        id: 'lager',
        question: 'Hur många röster?',
        type: 'choice',
        choices: [
          { id: '1', label: '1 röst', emoji: '🎤' },
          { id: '2', label: '2 röster', emoji: '🎤🎤' },
          { id: '4', label: '4 röster', emoji: '🎤🎤🎤🎤' },
        ],
      },
    ],
  },

  animation: {
    label: 'Animation',
    emoji: '🌀',
    color: '#f18f01',
    steps: [
      {
        id: 'karaktar',
        question: 'Vem är din karaktär?',
        type: 'choice',
        choices: [
          { id: 'ninja', label: 'Ninja', emoji: '🥷' },
          { id: 'robot', label: 'Robot', emoji: '🤖' },
          { id: 'katt', label: 'Katt', emoji: '🐱' },
          { id: 'dinosaurie', label: 'Dinosaurie', emoji: '🦕' },
          { id: 'enhornin', label: 'Enhörning', emoji: '🦄' },
          { id: 'pirat', label: 'Pirat', emoji: '🏴‍☠️' },
        ],
      },
      {
        id: 'bakgrund',
        question: 'Vilken bakgrund?',
        type: 'choice',
        choices: [
          { id: 'rymden', label: 'Rymden', emoji: '🚀' },
          { id: 'djungeln', label: 'Djungeln', emoji: '🌿' },
          { id: 'havet', label: 'Havet', emoji: '🌊' },
          { id: 'staden', label: 'Staden', emoji: '🏙️' },
          { id: 'dromvarlden', label: 'Drömvärlden', emoji: '✨' },
          { id: 'vulkanen', label: 'Vulkanen', emoji: '🌋' },
        ],
      },
      {
        id: 'rorelse',
        question: 'Hur rör sig karaktären?',
        type: 'choice',
        choices: [
          { id: 'hoppa', label: 'Hoppa', emoji: '🦘' },
          { id: 'dansa', label: 'Dansa', emoji: '💃' },
          { id: 'flyga', label: 'Flyga', emoji: '🕊️' },
          { id: 'snurra', label: 'Snurra', emoji: '🌀' },
          { id: 'vinka', label: 'Vinka', emoji: '👋' },
          { id: 'springa', label: 'Springa', emoji: '🏃' },
        ],
      },
      {
        id: 'effekter',
        question: 'Vilka effekter?',
        type: 'choice',
        choices: [
          { id: 'konfetti', label: 'Konfetti', emoji: '🎉' },
          { id: 'stjarnor', label: 'Stjärnor', emoji: '⭐' },
          { id: 'eld', label: 'Eld', emoji: '🔥' },
          { id: 'bubblor', label: 'Bubblor', emoji: '🫧' },
          { id: 'regnbage', label: 'Regnbåge', emoji: '🌈' },
          { id: 'blixt', label: 'Blixt', emoji: '⚡' },
        ],
      },
    ],
  },

  hemsida: {
    label: 'Min Hemsida',
    emoji: '🌐',
    color: '#3bb273',
    steps: [
      {
        id: 'stil',
        question: 'Vilken stil?',
        type: 'choice',
        choices: [
          { id: 'cool', label: 'Cool', emoji: '😎' },
          { id: 'sot', label: 'Söt', emoji: '🌸' },
          { id: 'spooky', label: 'Spooky', emoji: '👻' },
          { id: 'futuristisk', label: 'Futuristisk', emoji: '🤖' },
          { id: 'naturlig', label: 'Naturlig', emoji: '🌿' },
          { id: 'fargglad', label: 'Färgglad', emoji: '🌈' },
        ],
      },
      {
        id: 'avatar',
        question: 'Vilken avatar?',
        type: 'choice',
        choices: [
          { id: 'ninja', label: 'Ninja', emoji: '🥷' },
          { id: 'robot', label: 'Robot', emoji: '🤖' },
          { id: 'katt', label: 'Katt', emoji: '🐱' },
          { id: 'dinosaurie', label: 'Dinosaurie', emoji: '🦕' },
          { id: 'superhjälte', label: 'Superhjälte', emoji: '🦸' },
          { id: 'magiker', label: 'Magiker', emoji: '🧙' },
        ],
      },
      {
        id: 'favoriter',
        question: 'Välj 3 favoriter!',
        type: 'multiChoice',
        min: 3,
        max: 3,
        choices: [
          { id: 'musik', label: 'Musik', emoji: '🎵' },
          { id: 'sport', label: 'Sport', emoji: '⚽' },
          { id: 'djur', label: 'Djur', emoji: '🐾' },
          { id: 'mat', label: 'Mat', emoji: '🍕' },
          { id: 'spel', label: 'Spel', emoji: '🎮' },
          { id: 'bocker', label: 'Böcker', emoji: '📚' },
          { id: 'film', label: 'Film', emoji: '🎬' },
          { id: 'dans', label: 'Dans', emoji: '💃' },
        ],
      },
      {
        id: 'tema',
        question: 'Vilket färgtema?',
        type: 'choice',
        choices: [
          { id: 'rosa', label: 'Rosa', emoji: '🌸' },
          { id: 'bla', label: 'Blå', emoji: '🌊' },
          { id: 'gron', label: 'Grön', emoji: '🌿' },
          { id: 'lila', label: 'Lila', emoji: '💜' },
          { id: 'orange', label: 'Orange', emoji: '🔥' },
          { id: 'svart', label: 'Svart', emoji: '🌑' },
        ],
      },
    ],
  },
};
